steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile', '--tag=gcr.io/$PROJECT_ID/esc-master:$SHORT_SHA', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-f', 'Dockerfile.debian', '--tag=gcr.io/$PROJECT_ID/go:debian', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/esc-master:$SHORT_SHA', 'gcr.io/$PROJECT_ID/esc-master']

images:
- 'gcr.io/$PROJECT_ID/esc-master'
- 'gcr.io/$PROJECT_ID/esc-master:$SHORT_SHA'
